apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: gpu-job
        image: alpine:3.6
        resources:
            limits:
              # GiB
              aliyun.com/gpu-mem: 2
        command: ["sleep","30s"]
      restartPolicy: Never
